#!/bin/bash
# Device 03:20:08:05:2B:FC ZM T-12
# Device BA:98:76:A3:4E:BB Mivi DuoPods M40
# Device FC:D9:08:B6:39:C6 Redmi Note 10 Pro
# Device 4F:E7:B7:B0:26:D4 Airdopes-131

# initiate variables
device="$(bluetoothctl info | grep "Name" | cut -c 8-)" # check connected device
device_mac=""
device_sink=""
# function to connect Bluetooth
connectDevice () {
  rfkill block bluetooth
  sleep 1
  rfkill unblock bluetooth
  rfkill unblock all
  sleep 1
  bluetoothctl power on 
  bluetoothctl connect $1
  sleep 1
  pactl set-default-sink $2
}
# Airdopes 131
airdopes_mac="4F:E7:B7:B0:26:D4"
airdopes_sink="bluez_output.4F_E7_B7_B0_26_D4.a2dp-sink"

# Mivi Duopods
mivi_mac="BA:98:76:A3:4E:BB"
mivi_sink="bluez_output.BA_98_76_A3_4E_BB.a2dp-sink"

# Default
default_sink="alsa_output.pci-0000_00_1f.3.analog-stereo"

# Connect if no device found
if [[ -z $device ]]
then
  connectDevice $airdopes_mac $airdopes_sink || connectDevice $mivi_mac $mivi_sink || notify-send "No Bluetooth Headset Found"
else
	bluetoothctl power off && pactl set-default-sink $default_sink
  sleep 1
  rfkill block bluetooth
fi
# Update sbar
kill -34 "$(cat ~/.cache/pidofbar)"
kill -37 "$(cat ~/.cache/pidofbar)"
