#!/bin/sh

disk="$(lsblk -e7 -nr -o NAME,SIZE | tail -n +4| head -n -1 | rofi -dmenu -p "Mount Drives" -theme "$HOME/.config/rofi/launchers/text/style_2")"
diskToMount="$(printf $disk)"
if [ -z $diskToMount ]; then
  exit
else
mountTo="$(printf "/mnt\n/mnt/hd\n/mnt/pd" | rofi -dmenu -p "Mount To" -theme "$HOME/.config/rofi/launchers/text/style_2")"
fi

if [ -z "$disk" ]; then
  :
else
  doas mount /dev/"$diskToMount" "$mountTo"
  sudo chmod 777 "$mountTo"
  pcmanfm ~/ "$mountTo"
fi

kill -38 "$(cat ~/.cache/pidofbar)"
if [ $? -eq 0 ]; then
  notify-send "$diskToMount mounted to $mountTo" -t 2000
else
  notify-send "error in mounting disk" -u "critical" -t 2000
